### ISSUE TITLE
Это надо делать в каждом методе (т.к. иначе вы один раз при старте приложения загрузили и больше не получаете обновлённую информацию)

### ISSUE THREAD

**Issue by coursar** [dilyarakhabibullina/avito#2]
https://github.com/dilyarakhabibullina/avito/blob/87916b5706c6b648d9b57d7aee81eb1c3ea188db/src/main/java/ru/itpark/service/HouseService.java#L13-L24

**Comment by coursar** [comment]
Ну не так уж, сделайте метод `getAll`, который отдаёт все данные и из каждого метода вызывайте этот метод.

**Comment by dilyarakhabibullina** [comment]
Сделала метод getHouses, но не знаю, правильно или нет. Посмотрите пож-та. Еще вопрос- в начале сервиса получилось 2 почти одинаковых блока (см. ниже). Их нельзя как-то укоротить или объединить?
List<House> houses = JdbcTemplateV3.<House>executeQuery(
            "jdbc:sqlite:D:/domofond/src/main/resources\\db.sqlite",
            "SELECT id, name, district, price, underground, rooms, square FROM houses",
            resultSet -> new House(resultSet.getInt("id"),
                    resultSet.getString("name"),
                    resultSet.getString("district"),
                    resultSet.getInt("price"),
                    resultSet.getString("underground"),
                    resultSet.getInt("rooms"),
                    resultSet.getInt("square")
            )
    );

    public List<House> getHouses () throws SQLException {
        List<House> houses = JdbcTemplateV3.<House>executeQuery(
                "jdbc:sqlite:D:/domofond/src/main/resources\\db.sqlite",
                "SELECT id, name, district, price, underground, rooms, square FROM houses",
                resultSet -> new House(resultSet.getInt("id"),
                        resultSet.getString("name"),
                        resultSet.getString("district"),
                        resultSet.getInt("price"),
                        resultSet.getString("underground"),
                        resultSet.getInt("rooms"),
                        resultSet.getInt("square")
                )
        );
        return houses;
    }

**Comment by coursar** [comment]
Так объедините )) кто ж мешает
